[theme]
primaryColor = "#28255fff"   # A professional Indigo/Purple (instead of default red)
backgroundColor = "#000000ff" # Clean White
secondaryBackgroundColor = "#050b16ff" # Light Gray for sidebar
textColor = "#e8f7f7ff"       # Dark Gray (easier to read than pure black)
font = "sans serif"         # Modern font

[server]
headless = true
enableCORS = false