[theme]
primaryColor = "#8b5cf6"  # A professional Indigo/Purple (instead of default red)
backgroundColor = "#000000ff" 
secondaryBackgroundColor = "#050b16ff"
textColor = "#e8f7f7ff"     
font = "sans serif"         # Modern font

[server]
headless = true
enableCORS = false